### ISSUE TITLE
Documentation site returning 404 for many pages

### ISSUE THREAD

**Issue by gnunn1** [mayope/keycloakmigration#28]
Not sure what's going on, but visiting the documentation site seems to be returning 404 for many pages under migrations. For example, user migration works (https://mayope.github.io/keycloakmigration/migrations/user/) but groups (https://klg71.github.io/keycloakmigration/migrations/group/), clients, clientscopes do not. 

I noticing that the URLs using https://mayope.github.io/keycloakmigration work whereas the ones using https://klg71.github.io/keycloakmigration do not.

**Comment by klg71** [comment]
Hey @gnunn1 thanks for the issue. I fixed the baseUrl and it should be reachable again.

**Comment by klg71** [comment]
I close this issue cause I have tested all pages and so far they seem to work :)
