### ISSUE TITLE
add the ability to disable TLS certificate verification

### ISSUE THREAD

**Issue by raffaelespazzoli** [mayope/keycloakmigration#29]
In some environment certificates are generated internally and are not generally trusted.
An enhancement to this tool could be a flag to disable certificate validation. Many CLI tools use something like `--insecure-skip-tls-verify`.
Along the same line of thought options could be added to trust a specific cabundle .

**Comment by klg71** [comment]
I guess this would only be applicable for the docker image because if you use the fatJar version you should be able to configure it along the other jvm parameters. Did you try to use the jar version?

**Comment by raffaelespazzoli** [comment]
I'm using the fat jar version. In my situation it would be simple to just trust the cert as opposed to create a local truststore and configure it in the jvm parameters.

**Comment by klg71** [comment]
Well if its to inconvienient to add the certificate to the java keystore I think we could need this parameter. If you need it immediately you could file a pull request.
If not I guess, I can schedule it in a couple of weeks. :)
