### ISSUE TITLE
Support for default locale

### ISSUE THREAD

**Issue by aberg09** [mayope/keycloakmigration#56]
Hi,

at the moment it is possible to add locales for internationalization via a 'supportedLocales' list in the realm updater.
However, one cannot set the default locale.

In the rest API the according key is 'defaultLocale', e.g. defaultLocale: "English".
Is it possible to add this?

Thank you!

**Comment by klg71** [comment]
Hey aberg09 thanks for bringing up that topic :)
I guess we're talking about adding the parameter `defaultLocale` to this Action: https://mayope.github.io/keycloakmigration/migrations/realm/#updaterealm ?

**Comment by aberg09** [comment]
Thank you for replying so quickly.
yes, this is what I meant

**Comment by klg71** [comment]
Alright I'll be honest. If you want it done quick, you can prepare a pull request with your desired changes.
It should be fairly easy to add the parameter. You can begin by looking into `de.klg71.keycloakmigration.changeControl.actions.realm.UpdateRealmAction` :-)
If it isn't urgent I could probably implement it in a couple of weeks.

**Comment by aberg09** [comment]
Hi,
thanks for the hints. That is fair.
I have opened a pull request here: https://github.com/mayope/keycloakmigration/pull/57

**Comment by klg71** [comment]
Hey @aberg09 I merged your Merge Request :) I will release a new version as soon as your other Merge Request is completed :)

**Comment by aberg09** [comment]
Dear @klg71, thank you for the handling this so quickly and the great support! 
I am happy I could contribute a little bit.

**Comment by klg71** [comment]
Released with version: https://github.com/mayope/keycloakmigration/releases/tag/0.2.45
The release should be available on Mavencentral in 1-2 hours to 1 day.
Could you verify it works for you?
Thanks for your contribution :)

**Comment by aberg09** [comment]
I could successfully download the new version and it works as it should.
Thank you again. It has been nice working with you!
