### ISSUE TITLE
Support for client configurations

### ISSUE THREAD

**Issue by aberg09** [mayope/keycloakmigration#60]
Hello again :),

we have continued to set up our keycloak and came across some client setting that are not supported yet.
With your permission I would add them to the implementation via a pull request again.

The one we are lacking is _frontchannelLogout_.

However I also compared the REST API payload with the current documentation and found that some others are missing, too. I would add them as well.
Please let me know if there is something I should omit or something else we want to add to the list.

So I would add support for:
- _frontchannelLogout_ (the one we need)
- _consentRequired_
- _surrogateAuthRequired_ (not sure what field in the admin console this refers to)
- _alwaysDisplayInConsole_
- _notBefore_
- _nodeReRegistrationTimeout_ (not sure what field in the admin console this refers to)

(Most of the properties are already present in the Client class, but not yet in the UpdateClientAction class).

**Comment by klg71** [comment]
Hey aberg09 thanks for your commitment :)
I would be glad to receive such a completing Merge Request :)
Best Regards

**Comment by aberg09** [comment]
I am glad I can help.
And here is the pull request: https://github.com/mayope/keycloakmigration/pull/61

**Comment by klg71** [comment]
The change is released with version 0.2.46 (https://github.com/mayope/keycloakmigration/releases/tag/0.2.46) :) Thanks for your contribution. 👍

**Comment by aberg09** [comment]
The download works. Thanks again for making this happen so quickly!
