### ISSUE TITLE
Adding a role to the realm default roles

### ISSUE THREAD

**Issue by aberg09** [mayope/keycloakmigration#63]
Hi again,

I wonder if there is a way to add roles to the default roles for a realm (specifically a client role, if that should matter).
I have had a look at the REST Api and tried to replicate that with keycloakmigration using the updateRole. However, I could not get it running. 
Is this supported already?

Best regards

**Comment by klg71** [comment]
Hey @aberg09 thanks for opening an issue for this topic. I tried it out through the GUI in 18.0.2. In 18.0.2 default roles of a realm are simply another composite role where you can add your own roles to.
Did you try the `updateRole`-Action on the `default-roles-{realm}` realmRole? There is an option `compositeChildRoles` that expects a list of type `RoleSelector`. `RoleSelector` does have the attributes `name`(mandatory) and `clientId`(optional)
My own documentation is lacking in that case but I could work in my eyes :)
