### ISSUE TITLE
fat-jar als maven dependency

### ISSUE THREAD

**Issue by fadiaismael** [mayope/keycloakmigration#72]
Would it be possible to publish the fat-jar as a maven dependency? that would ease up the security scan and the update process on our side.
We also noticed that the last version is listed in the dependencies as 0.2.54 however in maven is the version 0.2.49, apparently there is here a version mismatch
thanks

**Comment by klg71** [comment]
Hey @fadiaismael thanks for bringing up the issue :) The unreleased versions puzzles me.
I released version [0.2.55](https://github.com/mayope/keycloakmigration/releases/tag/0.2.55) (https://repo.maven.apache.org/maven2/de/klg71/keycloakmigration/keycloakmigration/) it should be available soon in the maven search.
I don't really like the idea of fat-jars on maven central. (https://stackoverflow.com/questions/50179525/for-official-maven-repositories-do-people-release-fat-jars).
Could you use the docker image: https://hub.docker.com/r/klg71/keycloakmigration for your use-case?
