### ISSUE TITLE
Differences to keycloak-config-cli

### ISSUE THREAD

**Issue by skhro87** [mayope/keycloakmigration#74]
Hello,

I just discovered this project.

Currently I am using [keycloak-config-cli](https://github.com/adorsys/keycloak-config-cli) to have __configuration-as-code__ for Keycloak.

Now, I have some of questions:

- what are the differences/advantages of using your tool compared to the tool I mentioned? One difference is the configuration format (YAML vs JSON). Are there other differences/advantages?
- looking at the source code of your tool, it uses the Keycloak Admin REST API, with a client that you have implemented. Why not use the existing Keycloak Admin REST API Java SDK?

Please note that this are just questions, and no criticism. More tools are always good, and of course you are free to build your own tool. :)

Regards!

**Comment by klg71** [comment]
Hey @skhro87 I don't know the tool you mentioned and can't detail the differences between the two :/
I have implemented my own api because the original Java SDK is really hard to use in my eyes :)

**Comment by skhro87** [comment]
Alright @klg71 , that answers my questions! 
Thank you! :)
